services:
  hrms-ui:
    build: ./hrms-ui
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_AUTH_SERVICE_URL: "http://localhost:4001"
      NEXT_PUBLIC_EMPLOYEE_UI_URL: "http://localhost:3001"

  employee-ui:
    build: ./employee-onboarding/frontend
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_HRMS_URL: "http://localhost:3000"
      NEXT_PUBLIC_EMPLOYEE_UI_URL: "http://localhost:3001"

  employee-api:
    build: ./employee-onboarding/backend
    ports:
      - "4000:4000"
    environment:
      DB_HOST: mssql
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: "Kanishka#9810"
      DB_NAME: StingraysHRMS
    depends_on:
      mssql-init:
        condition: service_completed_successfully
      mssql:
        condition: service_started

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: stingrays-mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Kanishka#9810"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Kanishka#9810' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s

  mssql-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: stingrays-mssql-init
    environment:
      SA_PASSWORD: "Kanishka#9810"
    volumes:
      - ./init-sql:/scripts
    depends_on:
      mssql:
        condition: service_started
    command: /bin/bash /scripts/init-db.sh
    user: root

  auth-service:
    build: ./auth-service
    ports:
      - "4001:4000"
    environment:
      DB_HOST: mssql
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: "Kanishka#9810"
      DB_NAME: StingraysHRMS
      JWT_SECRET: "your-secret-key-change-this-in-production"
      PORT: 4000
    depends_on:
      mssql-init:
        condition: service_completed_successfully
      mssql:
        condition: service_started

volumes:
  mssql_data:  