FROM node:20-alpine
WORKDIR /workspace
COPY hrms-ui/package*.json hrms-ui/
WORKDIR hrms-ui
RUN npm ci --legacy-peer-deps
COPY hrms-ui .
COPY shared ./shared/
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
