USE StingraysHRMS;
GO

-- PayRuns: one per month/year (payslips generated by 2nd of each month)
IF OBJECT_ID('PayRuns', 'U') IS NULL
BEGIN
    CREATE TABLE PayRuns (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        Month INT NOT NULL,
        Year INT NOT NULL,
        Status NVARCHAR(50) NOT NULL DEFAULT 'draft',
        CreatedAt DATETIME DEFAULT GETDATE(),
        FinalizedAt DATETIME NULL,
        CONSTRAINT UQ_PayRuns_MonthYear UNIQUE (Month, Year)
    );
    PRINT 'Table PayRuns created';
END
GO

-- Payslips: linked to PayRun and Employee; columns match requirements (dynamic-friendly)
IF OBJECT_ID('Payslips', 'U') IS NULL
BEGIN
    CREATE TABLE Payslips (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        PayRunId INT NOT NULL,
        EmployeeId INT NOT NULL,
        Month INT NOT NULL,
        Year INT NOT NULL,
        WorkingDays DECIMAL(10,2) NOT NULL DEFAULT 0,
        WorkingHours DECIMAL(10,2) NOT NULL DEFAULT 0,
        BasicContractorFee DECIMAL(18,2) NOT NULL DEFAULT 0,
        Profit121 DECIMAL(18,2) NOT NULL DEFAULT 0,
        Allowances DECIMAL(18,2) NOT NULL DEFAULT 0,
        WeekendWeekdaysProfitShare DECIMAL(18,2) NOT NULL DEFAULT 0,
        OT DECIMAL(18,2) NOT NULL DEFAULT 0,
        Commission DECIMAL(18,2) NOT NULL DEFAULT 0,
        Admin DECIMAL(18,2) NOT NULL DEFAULT 0,
        Outsourced DECIMAL(18,2) NOT NULL DEFAULT 0,
        Deductions DECIMAL(18,2) NOT NULL DEFAULT 0,
        Total DECIMAL(18,2) NOT NULL DEFAULT 0,
        NetPay DECIMAL(18,2) NOT NULL DEFAULT 0,
        CreatedAt DATETIME DEFAULT GETDATE(),
        CONSTRAINT FK_Payslips_PayRun FOREIGN KEY (PayRunId) REFERENCES PayRuns(Id) ON DELETE CASCADE,
        CONSTRAINT FK_Payslips_Employee FOREIGN KEY (EmployeeId) REFERENCES Employees(Id),
        CONSTRAINT UQ_Payslips_PayRun_Employee UNIQUE (PayRunId, EmployeeId)
    );
    PRINT 'Table Payslips created';
END
GO

-- TaxBrackets: dynamic tax rules (MinAmount, MaxAmount, RatePercent)
IF OBJECT_ID('TaxBrackets', 'U') IS NULL
BEGIN
    CREATE TABLE TaxBrackets (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        Name NVARCHAR(100) NOT NULL,
        MinAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
        MaxAmount DECIMAL(18,2) NOT NULL,
        RatePercent DECIMAL(5,2) NOT NULL DEFAULT 0,
        CreatedAt DATETIME DEFAULT GETDATE()
    );
    PRINT 'Table TaxBrackets created';
END
GO

-- DeductionRules: global rules (percentage or fixed); configurable per employee via overrides
IF OBJECT_ID('DeductionRules', 'U') IS NULL
BEGIN
    CREATE TABLE DeductionRules (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        Name NVARCHAR(100) NOT NULL UNIQUE,
        Type NVARCHAR(20) NOT NULL,
        DefaultValue DECIMAL(18,2) NOT NULL DEFAULT 0,
        CreatedAt DATETIME DEFAULT GETDATE(),
        CONSTRAINT CK_DeductionRules_Type CHECK (Type IN ('percentage', 'fixed'))
    );
    PRINT 'Table DeductionRules created';
END
GO

-- EmployeeDeductionOverrides: per-employee deduction (overrides rule default)
IF OBJECT_ID('EmployeeDeductionOverrides', 'U') IS NULL
BEGIN
    CREATE TABLE EmployeeDeductionOverrides (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        EmployeeId INT NOT NULL,
        DeductionRuleId INT NOT NULL,
        OverrideValue DECIMAL(18,2) NOT NULL,
        CreatedAt DATETIME DEFAULT GETDATE(),
        CONSTRAINT FK_EmployeeDeductionOverrides_Employee FOREIGN KEY (EmployeeId) REFERENCES Employees(Id) ON DELETE CASCADE,
        CONSTRAINT FK_EmployeeDeductionOverrides_Rule FOREIGN KEY (DeductionRuleId) REFERENCES DeductionRules(Id) ON DELETE CASCADE,
        CONSTRAINT UQ_EmployeeDeductionOverrides UNIQUE (EmployeeId, DeductionRuleId)
    );
    PRINT 'Table EmployeeDeductionOverrides created';
END
GO

PRINT 'Payroll schema completed';
GO
